name:  Build and push image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    name: build and push image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push image
        run: |
          docker buildx create --name awx-ee-buildx
          docker buildx use awx-ee-buildx
          ansible-builder create -v3 --output-file=Dockerfile
          docker buildx build \
            --push \
            --platform=linux/amd64 \
            --tag=ghcr.io/${{ github.repository_owner }}/awx-ee-pyVmomi:latest \
            context
